config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :pathways, only: [:index, :show] do
    resources :bookmarks, only: [:create]
  end
  resources :user_skills, only: [:new, :create]
  resources :user_values, only: [:new, :create]
  resources :bookmarks, only: [:destroy, :update]

  patch "/user_skills_level", to: "user_skills#update_level", as: :update_level
  get "/dashboard", to: "dashboards#dashboard"
  get "/assessment", to: "pages#assessment"
  get "/recommendations/create", to: "recommendations#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :pathway
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :recommended_courses
  validates :title, presence: true
  validates :description, presence: true
  validates :url, presence: true
  validates :rating, presence: true
end

app/models/pathway.rb
class Pathway < ApplicationRecord
  has_many :recommended_pathways
  has_many :recommended_courses
  has_many :courses, through: :recommended_courses
  has_many :bookmarks
  has_many :pathway_skills
  has_many :skills, through: :pathway_skills
  has_many :skill_categories, through: :skills

  validates :name, presence: true
  validates :description, presence: true
  validates :description_short, presence: true
  validates :category, presence: true
  validates :suit_for, presence: true
  validates :job_roles, presence: true
  validates :avg_salary, presence: true
  validates :avg_salary, numericality: { only_integer: true }
  validates :projected_growth, presence: true
  validates :projected_growth, length: { minimum: 2 }
end

app/models/pathway_skill.rb
class PathwaySkill < ApplicationRecord
  belongs_to :pathway
  belongs_to :skill
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :user
  has_many :recommended_pathways
  has_many :pathways, through: :recommended_pathways
end

app/models/recommended_course.rb
class RecommendedCourse < ApplicationRecord
  belongs_to :course
  belongs_to :pathway
end

app/models/recommended_pathway.rb
class RecommendedPathway < ApplicationRecord
  belongs_to :recommendation
  belongs_to :pathway
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :skill_category
  has_many :user_skills
end

app/models/skill_category.rb
class SkillCategory < ApplicationRecord
  has_many :skills
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recommendations
  has_many :recommended_pathways, through: :recommendations
  has_many :pathways, through: :recommended_pathways
  has_many :recommended_courses, through: :pathways
  has_many :courses, through: :recommended_courses
  has_many :user_skills
  has_many :user_values
  has_many :skills, through: :user_skills
  has_many :bookmarks
  has_many :values, through: :user_values

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :skill
  belongs_to :user

  validates :user, uniqueness: {scope: :skill}

end

app/models/user_value.rb
class UserValue < ApplicationRecord
  belongs_to :user
  belongs_to :value
  validates :user, uniqueness: {scope: :value}
end

app/models/value.rb
class Value < ApplicationRecord
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:update, :destroy]

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.user = current_user
    @bookmark.pathway = Pathway.find(params[:pathway_id])
    if @bookmark.save
      redirect_to pathway_path(@bookmark.pathway, anchor: "bookmarks"), notice: "Done"
    else
      render "pathways/show", status: :unprocessable_entity
    end
  end

  def update
    @bookmark.update(bookmark_params)
    redirect_to pathway_path(@bookmark.pathway)
  end

  #delete
  def destroy
    @bookmark.destroy
    redirect_to pathway_path(@bookmark.pathway), notice: "The bookmark was deleted."
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:note)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def dashboard
    # total = 100
    # @progress_chart = {
    #   "Quiz" => current_user.recommendations.any? ? 50 : 0,
    #   "Skills Assessment" => current_user.skills.any? ? 25 : 0,
    #   "Values Assessment" => current_user.values.any? ? 25 : 0,
    #   # "Take Assessments to get matches": 000,
    #   "Take Assessments" => 0
    # }
    # @progress_chart["Take Assessments"] = total - @progress_chart["Quiz"] - @progress_chart["Skills Assessment"] - @progress_chart["Values Assessment"]
    @progress = [
      current_user.recommendations.any? ? 50 : 0,
      current_user.skills.any? ? 25 : 0,
      current_user.values.any? ? 25 : 0
    ]
    if @progress.sum == 50
      @progress_class = "half"
    elsif @progress.sum == 75
      @progress_class = "three-q"
    elsif @progress.sum == 100
      @progress_class = "full"
    end

    @result_chart = Pathway.group(:name).count

    @user_value = UserValue.new
    @user_values = current_user.user_values.order(importance: :desc).limit(5)

    @user_skill = UserSkill.new
    @user_skills = current_user.skills

    @recommendation = Recommendation.where(user: current_user).order(created_at: :desc).first
    @recommended_pathways = RecommendedPathway.where(recommendation: @recommendation).order(match_score: :desc).first(5)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @pathways = Pathway.all
  end

  def assessment
  end
end

app/controllers/pathways_controller.rb
class PathwaysController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @pathways = Pathway.all
  end

  def show
    @bookmark = Bookmark.new
    @pathway = Pathway.find(params[:id])
    if user_signed_in?
      @existing_bookmarks = current_user.bookmarks.where(pathway: @pathway)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">


    <link rel="icon" type="image/x-icon" href="<%= image_path 'favicon.ico' %>">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/_howto.html.erb
<div class="home-section-2">
  <div class="container">
    <div class="py-5">
      <div class="steps">
        <h2 class="my-5">How It Works</h2>
        <div class="cards py-5">
          <div class="how-to-card">
            <%= image_tag "Sign Up_imag.svg" %>
            <h2>1.</h2>
            <h3>Sign Up</h3>
          </div>
          <div class="how-to-card">
            <%= image_tag "Quiz_1.svg" %>
            <h2>2.</h2>
            <h3>Take Quiz</h3>
          </div>
          <div class="how-to-card">
            <%= image_tag "recommendation_imag.svg" %>
            <h2>3.</h2>
            <h3>Get Recommendations</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/assessment.html.erb
<div id="typeform-wrapper" data-tf-hidden="name=<%= current_user.first_name %>" data-tf-widget="DfXB0zI2" data-tf-on-submit="onSubmit">
</div>
<script>
  function onSubmit(event) {
    // console.log(event);
    const response_id = event.response_id;
    window.location.replace(`/recommendations/create?response_id=${response_id}`);
  }
</script>
<script src="//embed.typeform.com/next/embed.js"></script>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/3727459/pexels-photo-3727459.jpeg);">
  <div class="container">
    <h1><span data-controller="typed-js"></span></h1>
    <p class="mt-4">We help you find out which is the best career in Technology for you.<br>Change your life, future-proof your career and get started today!!</p>
    <% if user_signed_in? && current_user.recommendations.any? %>
      <button class="button-pri mt-5"><%= link_to "Get Started", dashboard_path %></button>
    <% elsif current_user && current_user.recommendations.empty? %>
      <button class="button-pri mt-5"><%= link_to "Get Started", assessment_path %></button>
    <% else %>
      <button class="button-pri mt-5"><%= link_to "Let's do this!", new_user_registration_path%></button>
    <% end %>
  </div>
</div>

<%= render "howto" %>

<div class="container">
  <div>
    <h2 class="my-5 py-5">Explore the most in-demand career pathways in Technology</h2>
  </div>

  <div class="grid">
    <% @pathways.sample(3).each do |pathway| %>
      <%= render "shared/path_card", pathway: pathway %>
    <% end %>
  </div>

  <div class="my-5 py-5 btn-pathways">
    <%= link_to "See all pathways", pathways_path, class: "button-sec" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="d-flex justify-content-between align-items-start">
    <div class="about-app">
      <h4>About the App</h4>
      <p>The Digital Compass is part of the project <strong><%= link_to "she explores tech", "https://www.sheexplores.tech/", target: :_blank %></strong>, which is in a mission to increase diversity in Tech in Switzerland. By using tools powered by artificial intelligence and harnessing the power of mentorship and community, we empower women with career exploration, reskilling and job placement.</p>
    </div>
    <div class="social-links">
      <div class="d-flex justify-content-between">
        <%= link_to "https://www.linkedin.com/company/she-explores-tech/" do %>
          <img alt="LinkedIn" style="width: 25px; height: 25px; object-fit: cover;" fetchpriority="high" src="https://static.wixstatic.com/media/aa0402eb9ba2430d9d0620b59556efca.png/v1/fill/w_25,h_25,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/aa0402eb9ba2430d9d0620b59556efca.png">
        <% end %>
        <%= link_to "https://www.instagram.com/sheexplorestech/" do %>
        <img alt="Instagram" style="width: 25px; height: 25px; object-fit: cover;" fetchpriority="high" src="https://static.wixstatic.com/media/e1aa082f7c0747168d9cf43e77046142.png/v1/fill/w_25,h_25,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/e1aa082f7c0747168d9cf43e77046142.png">          <% end %>
      </div>
    </div>
    <div class="quick-links">
      <h4>Quick Links</h4>
      <div class="d-flex flex-column align-items-end">
        <%= link_to "Home", root_path %>
        <%= link_to "Dashboard", dashboard_path %>
        <%= link_to "Explore Pathways", pathways_path %>
        <%= link_to "Contact us", "#" %>
        <%= link_to "Log Out", destroy_user_session_path, data: { "turbo-method": :delete } %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dc">
  <div class="d-flex justify-content-between w-100 mx-3">
    <div class="d-flex align-items-center">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "DigitalCompass logo wine long.png" %>
      <% end %>
      <%# <div class="logo-text">
        <p>DIGITAL</p>
        <p>COMPASS</p>
      </div> %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="nav-links d-flex align-items-center">
      <% if user_signed_in? %>
        <% if current_user.recommendations.empty? %>
          <button class="button-pri mx-4"><%= link_to "Take the quiz", assessment_path %></button>
        <% end %>
        <%= link_to "Explore Pathways", pathways_path, class: "mx-4" %>
        <%= link_to "Dashboard", dashboard_path, class: "mx-4" %>
        <%= link_to destroy_user_session_path, data: { "turbo-method": :delete }, class: "mx-4" do %>
          <i class="fa-solid fa-arrow-right-from-bracket"></i>
        <% end %>
      <% else %>
        <%= link_to "Explore Pathways", pathways_path, class: "mx-4" %>
        <button class="button-pri mx-4"><%= link_to "Sign Up", new_user_registration_path %></button>
        <button class="button-sec mx-4"><%= link_to "Log In", new_user_session_path %></button>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_path_card.html.erb
<div class="artboard">
 <div class="card">

  <div class="card__side card__side--back">
   <div class="card__cover">
    <h4 class="card__heading">
     <span class="card__heading-span"><%= pathway.name %></span>
    </h4>
   </div>
   <div class="card__details">
    <ul mb-3>
     <li><%= pathway.description_short %></li>
     <li>Average Salary: Fr. <%= pathway.avg_salary %></li>
     <li class="mb-3">Projected Job Growth: <%= pathway.projected_growth %></li>
     <li class="pt-5"><%= link_to "Learn More >", pathway_path(pathway), class: "button-sec" %></li>
    </ul>
   </div>
  </div>

  <div class="card__side card__side--front">
   <div class="card__theme">
    <div class="card__theme-box">
     <p class="card__subject">CAREER PATH</p>
     <p class="card__title"><%= pathway.name %></p>
    </div>
   </div>
  </div>

 </div>
</div>