config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :pathways, only: [:index, :show] do
    resources :bookmarks, only: [:create]
  end
  resources :user_skills, only: [:new, :create]
  resources :user_values, only: [:new, :create]
  resources :bookmarks, only: [:destroy, :update]

  patch "/user_skills_level", to: "user_skills#update_level", as: :update_level
  get "/dashboard", to: "dashboards#dashboard"
  get "/assessment", to: "pages#assessment"
  get "/recommendations/create", to: "recommendations#create"
end

app/models/pathway.rb
class Pathway < ApplicationRecord
  has_many :recommended_pathways
  has_many :recommended_courses
  has_many :courses, through: :recommended_courses
  has_many :bookmarks
  has_many :pathway_skills
  has_many :skills, through: :pathway_skills
  has_many :skill_categories, through: :skills

  validates :name, presence: true
  validates :description, presence: true
  validates :description_short, presence: true
  validates :category, presence: true
  validates :suit_for, presence: true
  validates :job_roles, presence: true
  validates :avg_salary, presence: true
  validates :avg_salary, numericality: { only_integer: true }
  validates :projected_growth, presence: true
  validates :projected_growth, length: { minimum: 2 }
end

app/controllers/pathways_controller.rb
class PathwaysController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @pathways = Pathway.all
  end

  def show
    @bookmark = Bookmark.new
    @pathway = Pathway.find(params[:id])
    if user_signed_in?
      @existing_bookmarks = current_user.bookmarks.where(pathway: @pathway)
    end
  end
end

app/views/pathways/index.html.erb
<div class="container">
  <div>
    <h2 class="my-5 py-5 text-center">Future-proof your career by getting into Tech</h2>
  </div>

  <div class="container mb-5">
    <p>According to Swiss ICT, there is a shortage of skilled IT workers and for every unemployed ICT specialist, there are four vacancies.
    The Swiss economy will need 117,900 additional ICT specialists by 2028.
    This means that demand is currently out-stripping supply.</p>
    <p>ICT is the seventh largest professional field in Switzerland and the number of ICT workers is still growing 2.5 times quicker than the total number of employees.
    So, these are great times to consider a career change or a lateral entry into Tech.
    If you are still not sure which path may be the best for you, make sure to <strong><%= link_to "sign-up", new_user_registration_path, class: "real-link" %></strong> and start by taking our tech-personality quiz.</p>
  </div>
  <h3 class="my-5 py-5"> Check out these in-demand career pathways:</h3>
    <div class="grid">
      <% @pathways.each do |pathway| %>
        <%= render "shared/path_card", pathway: pathway %>
      <% end %>
    </div>

    <h4 class="my-5 py-5">More pathways coming soon...</h4>

</div>

app/views/pathways/show.html.erb
<div class="container">
  <div class="my-5 py-5">
    <h2 class="mb-5 title-path-border">
    <div class="show-title-bookmark">
      <div class="pathway-name">
        <%= @pathway.name %>
      </div>
      <div class="bookmark-icon">
        <% if user_signed_in? %>
          <%= link_to "#bookmarks" do  %>
            <% if @existing_bookmarks.empty? %>
              <i class="fa-regular fa-bookmark bookmark-icon" ></i>
            <% else %>
              <i class="fa-solid fa-bookmark bookmark-icon"></i>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    </h2>
    <%# <h4>Category: <%= @pathway.category %></h4>
    <h4>Average Yearly Salary:  Fr. <%= @pathway.avg_salary %></h4>
    <h4 class="pt-3">Projected Job Growth: <%= @pathway.projected_growth %></h4>
  </div>

  <div class="showpage-columns">
    <div class="column-one">
      <div>
        <p><%= @pathway.description %></p>
        <p class="pt-3"><%= @pathway.suit_for %></p>
      </div>
    </div>

    <div class="column-two">
      <div>
        <%= image_tag "woman-coding.jpg", class: "img-thumbnail" %>
        <div>
          <h3 class="my-5">Possible Job Roles:</h3>
          <p><%= @pathway.job_roles %></p>
        </div>
      </div>
    </div>
  </div>

  <div>
    <h3 class="my-5">Main skills required:</h3>
    <% @pathway.skills.each do |skill| %>
      <p class="skills-showpage"><%= skill.name %></p>
    <% end %>
  </div>

  <div>
    <h3 class="my-5">Recommended Courses:</h3>
    <div class="grid mb-5">
      <% @pathway.courses.each do |course| %>
        <div class="result-card pathway_course_bg p-5 text-center">
          <h4 class="mb-5"><%=course.title %></h4>
          <p><%=course.description %></p>
          <div class="d-flex justify-content-between ratingandlink">
            <p><strong>Rating:</strong> <%=course.rating %></p>
            <%= link_to "Go to Course", course.url, class: "real-link", target: :_blank %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%# add form to create a new @bookmark with column :note %>
    <div class="bookmark-container">
      <% if user_signed_in? %>
      <h3 class="my-5">Your personal notes:</h3>
        <%= simple_form_for [@pathway, @bookmark], html: { data: { turbo: false } } do |f| %>
          <%= f.input :note, label: false %>
          <div class="button-position">
            <%= f.button :submit, 'Save', class: "button-sec" %>
          </div>
        <% end %>
        <div id="bookmarks">
          <% @existing_bookmarks.each do |bookmark| %>
          <div class="bookmark-note">
            <div class="bookmark-note1">
              <%= bookmark.note %>
            </div>
            <div class="edit-delete-icons">
              <div data-controller="reveal" class="w-100" data-reveal-hidden-class="d-none">
                <div class="d-flex align-items-center justify-content-end">
                  <button data-action="click->reveal#toggle" type="button" class="btn"><i class="fa-solid fa-pencil"></i></button>
                  <%= button_to bookmark_path(bookmark), method: "delete", class: "btn" do %>
                    <i class="fa-regular fa-trash-can fa-2x"></i>
                  <% end %>
                </div>
                <div data-reveal-target="item" class="d-none mt-4">
                  <%= simple_form_for bookmark, html: { data: { turbo: false } } do |f| %>
                    <%= f.input :note, label: false %>
                    <div class="button-position">
                      <%= f.button :submit, 'Save', class: "button-sec" %>
                    </div>
                  <% end %>
                </div>

              </div>
            </div>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

</div>