config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :pathways, only: [:index, :show] do
    resources :bookmarks, only: [:create]
  end
  resources :user_skills, only: [:new, :create]
  resources :user_values, only: [:new, :create]
  resources :bookmarks, only: [:destroy, :update]

  patch "/user_skills_level", to: "user_skills#update_level", as: :update_level
  get "/dashboard", to: "dashboards#dashboard"
  get "/assessment", to: "pages#assessment"
  get "/recommendations/create", to: "recommendations#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :pathway
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :recommended_courses
  validates :title, presence: true
  validates :description, presence: true
  validates :url, presence: true
  validates :rating, presence: true
end

app/models/pathway.rb
class Pathway < ApplicationRecord
  has_many :recommended_pathways
  has_many :recommended_courses
  has_many :courses, through: :recommended_courses
  has_many :bookmarks
  has_many :pathway_skills
  has_many :skills, through: :pathway_skills
  has_many :skill_categories, through: :skills

  validates :name, presence: true
  validates :description, presence: true
  validates :description_short, presence: true
  validates :category, presence: true
  validates :suit_for, presence: true
  validates :job_roles, presence: true
  validates :avg_salary, presence: true
  validates :avg_salary, numericality: { only_integer: true }
  validates :projected_growth, presence: true
  validates :projected_growth, length: { minimum: 2 }
end

app/models/pathway_skill.rb
class PathwaySkill < ApplicationRecord
  belongs_to :pathway
  belongs_to :skill
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :user
  has_many :recommended_pathways
  has_many :pathways, through: :recommended_pathways
end

app/models/recommended_course.rb
class RecommendedCourse < ApplicationRecord
  belongs_to :course
  belongs_to :pathway
end

app/models/recommended_pathway.rb
class RecommendedPathway < ApplicationRecord
  belongs_to :recommendation
  belongs_to :pathway
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :skill_category
  has_many :user_skills
end

app/models/skill_category.rb
class SkillCategory < ApplicationRecord
  has_many :skills
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recommendations
  has_many :recommended_pathways, through: :recommendations
  has_many :pathways, through: :recommended_pathways
  has_many :recommended_courses, through: :pathways
  has_many :courses, through: :recommended_courses
  has_many :user_skills
  has_many :user_values
  has_many :skills, through: :user_skills
  has_many :bookmarks
  has_many :values, through: :user_values

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :skill
  belongs_to :user

  validates :user, uniqueness: {scope: :skill}

end

app/models/user_value.rb
class UserValue < ApplicationRecord
  belongs_to :user
  belongs_to :value
  validates :user, uniqueness: {scope: :value}
end

app/models/value.rb
class Value < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:update, :destroy]

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.user = current_user
    @bookmark.pathway = Pathway.find(params[:pathway_id])
    if @bookmark.save
      redirect_to pathway_path(@bookmark.pathway, anchor: "bookmarks"), notice: "Done"
    else
      render "pathways/show", status: :unprocessable_entity
    end
  end

  def update
    @bookmark.update(bookmark_params)
    redirect_to pathway_path(@bookmark.pathway)
  end

  #delete
  def destroy
    @bookmark.destroy
    redirect_to pathway_path(@bookmark.pathway), notice: "The bookmark was deleted."
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:note)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def dashboard
    # total = 100
    # @progress_chart = {
    #   "Quiz" => current_user.recommendations.any? ? 50 : 0,
    #   "Skills Assessment" => current_user.skills.any? ? 25 : 0,
    #   "Values Assessment" => current_user.values.any? ? 25 : 0,
    #   # "Take Assessments to get matches": 000,
    #   "Take Assessments" => 0
    # }
    # @progress_chart["Take Assessments"] = total - @progress_chart["Quiz"] - @progress_chart["Skills Assessment"] - @progress_chart["Values Assessment"]
    @progress = [
      current_user.recommendations.any? ? 50 : 0,
      current_user.skills.any? ? 25 : 0,
      current_user.values.any? ? 25 : 0
    ]
    if @progress.sum == 50
      @progress_class = "half"
    elsif @progress.sum == 75
      @progress_class = "three-q"
    elsif @progress.sum == 100
      @progress_class = "full"
    end

    @result_chart = Pathway.group(:name).count

    @user_value = UserValue.new
    @user_values = current_user.user_values.order(importance: :desc).limit(5)

    @user_skill = UserSkill.new
    @user_skills = current_user.skills

    @recommendation = Recommendation.where(user: current_user).order(created_at: :desc).first
    @recommended_pathways = RecommendedPathway.where(recommendation: @recommendation).order(match_score: :desc).first(5)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @pathways = Pathway.all
  end

  def assessment
  end
end

app/controllers/pathways_controller.rb
class PathwaysController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @pathways = Pathway.all
  end

  def show
    @bookmark = Bookmark.new
    @pathway = Pathway.find(params[:id])
    if user_signed_in?
      @existing_bookmarks = current_user.bookmarks.where(pathway: @pathway)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/dashboards/_overviewtab.html.erb
<div class="content-overview">
  <div class="overview-first-line">
    <div class="progress-chart">
      <h3>Progress</h3>
      <%= render "dashboards/progress" %>

      <div class="my-5 mb-2 progress-text">
        <i class="fa-solid fa-circle-info"></i>
        <p>Complete the Quiz, Skills and Values Assessment to advance your progression</p>
      </div>
    </div>

    <div class="quiz-results-chart">
      <h3 class="mb-5">Your Top Pathway Matches</h3>
      <% if @recommended_pathways.empty? %>
        <div class="no-quiz">
          <p>No recommendations yet.</p>
          <%= link_to "You can take the initial quiz here.", assessment_path %>
        </div>
      <% else %>
        <div class="pw-bar-chart">
          <% opa = 1.0 %>
          <% @recommended_pathways.each do |recommended_pathway| %>
            <%= link_to pathway_path(recommended_pathway.pathway) do %>
              <div class="pw-bar" style="width: <%= recommended_pathway.match_score %>%; opacity: <%= opa %>">
                <p class="pw-name"><%= recommended_pathway.pathway.name %></p>
                <p class="pw-score"><%= recommended_pathway.match_score %> %</p>
              </div>
              <% opa -= 0.1 %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="overview-second-line" id="test">
    <div class="overview-skills">
      <h3>Your Skills</h3>
        <% if @user_skills.empty? %>
          <p>No skills added yet.</p>
          <%= link_to "You can add your skills here.", new_user_skill_path %>
        <% else %>
          <div class="skills-capsules">
            <% @user_skills.first(15).each do |skill| %>
              <p class="skill-stack"><%= skill.name %></p>
            <% end %>
          </div>
        <% end %>
    </div>


    <div class="values-chart">
      <h3>Your Top 5 Work Values</h3>
      <% if @user_values.where("importance > 0").empty? %>
        <p>No values added yet.</p>
        <%= link_to "You can add your values here.", dashboard_path(tab: "Values") %>
      <% else %>
        <% @user_values.where("importance > 0").order(importance: :desc).first(5).each do |uv| %>
          <p class="value-stack"><%= uv.value.name %></p>
        <% end %>
      <% end %>
      <%#= bar_chart @user_values, download: "bar-chart", colors: ["#6E184F", "#716F35", "#DB9A8F", "#ECCC6E", "#A66940", "#F2E9E1", "#FCE8D2", "#E9E9E9", "#0E1251"] %>
    </div>
  </div>
</div>

app/views/dashboards/_progress.html.erb
<div class="progress-circle">
  <div class="">
    <div class="mt-5 progress blue">
        <span class="progress-left">
            <span class="progress-bar <%= @progress_class %>"></span>
        </span>
        <span class="progress-right">
            <span class="progress-bar <%= "empty" if @progress.sum == 0 %><%= "one-q" if @progress.sum == 25 %>  "></span>
        </span>
        <div class="progress-value"> <%= @progress.sum %>%</div>
    </div>
  </div>
</div>

app/views/dashboards/_skillstab.html.erb
<div class="skills-intro container">
  <h3 class="h3-skills">Assess your current skills to improve our career recommendations</h3>
  <p>
  1. Add skills by clicking on the Add More button and selecting  skills you currently have. <br>
  2. Use the slider to assess your mastery level (0-3). <br>
  3. Click on the Book icon if you are specially interested in learning more about that specific skill. <br>
  4. Finally, click on submit to save your answers. <br> <br>
  Note: As you progress in your tech career, you can always come back here and add more skills or edit your answers. To delete a skill just unmark it.
  </p>
</div>

<div class="skills-tab-content">
  <div class="skills-table" data-controller="skills-slider">
    <div class="headers-skills">
      <p>Skill</p>
      <p>Mastery level</p>
      <p>Learning interest</p>
    </div>

    <%= simple_form_for @user_skill, url: update_level_path, method: :patch do |f| %>
      <% @user_skills.each do |skill| %>
        <% user_skill = current_user.user_skills.find_by(skill: skill) %>
        <div class="one-skill-row">
            <p><%= skill.name %></p>
            <div class="col-3 slider-simple">
              <input type="range" class="form-range" value="<%= user_skill.mastery_level ? user_skill.mastery_level : 0 %>" min="0" max="3" step="1" data-id="<%= skill.id %>" data-action="change->skills-slider#sliderValue" name="user_skill[mastery_level][<%= skill.id %>]">
            </div>
            <span id="value-<%= skill.id %>" class="selected_value"><%= user_skill.mastery_level ? user_skill.mastery_level : 0 %></span>

            <input
              class="book-checkbox <%= "active" if user_skill.learning_interest %>"
              type="checkbox"
              id="interest-<%= skill.id %>"
              name="user_skill[learning_interest][<%= skill.id %>]"
              <%= "checked" if user_skill.learning_interest %>
              value="Book">
            <label for="interest-<%= skill.id %>"> <i class="fa-solid fa-book-open"></i> </label>

          </div>
        <% end %>
      <div class="button-sec button-save-center">
        <%= f.submit 'Save', class: "save-btn-skills" %>
      </div>
    <% end %>
  </div>

  <div class="button-add-skills">
    <div class="button-pri">
      <%= link_to "Add more...", new_user_skill_path %>
    </div>
  </div>
</div>

app/views/dashboards/_valuestab.html.erb
<div>
  <h3 class="pb-3">Workplace Values Assessment</h3>
  <p>People expect to achieve certain ideals from their jobs employers and careers. These workplace values concepts and ideas that you hold dear have a direct impact on your satisfaction with your job with your career and even with your life. When you understand the values you cherish most highly you can make an evaluation about whether your current employer (or a prospective employer) supports those values. And if you are considering a career change understanding your values is critical to identifying a new career path.</p>
</div>
<div class="ms-3 my-5">
  <p>1️. - Rate the degree of importance that you place on each of the following workplace values, using this scale:</p>
  <div class="ms-5">
   <ul><p><strong>0 = Not important to me at all → 5 = Very important to me</p></strong></ul>
  </div>
  <p>2️. - Double check which are your top rated values (those with 4 and 5 stars) and try to reduce them to maximum 5 -- only the ones you really cannot live without.</p>
  <p>3. - Click on Submit to save your selection.</p>
</div>

<div class="row my-5 py-3">
<h4 class="pb-3">I am interested in jobs and careers that include...</h4>
  <% if @user_values.empty? %>
    <%= simple_form_for @user_value do |f| %>
      <% Value.all.each do |value| %>
        <div class="value">
          <p><%= f.input :importance,
                        collection: (1..5).to_a,
                        label: "#{value.name}",
                        input_html: {data: {controller: "star-rating"}, name: "user_value[value][#{value.id}]"}%></p>
        </div>
      <% end %>
      <%= f.button :submit, "Submit", class: "button-sec" %>
    <% end %>
  <% else %>
    <%= simple_form_for @user_value do |f| %>
      <% Value.all.each do |value| %>
        <div class="value">
          <p><%= f.input :importance,
                        collection: (0..5).to_a,
                        label: "#{value.name}",
                        selected: @user_values.find_by(value: value) ? @user_values.find_by(value: value).importance : 0,
                        input_html: {data: {controller: "star-rating"}, name: "user_value[value][#{value.id}]"}%></p>
        </div>
      <% end %>
      <%= f.button :submit, "Submit", class: "button-sec" %>
    <% end %>
  <% end %>
</div>


<h3 class="my-3 py-3">Congratulations!</h3>
<p>You now have a list of core workplace value that represent who you are... it is this core group of workplace values that help determine your level of satisfaction with your job and your career - and which should be used to judge the level of "fit" with any future job company or career change.</p>

app/views/dashboards/dashboard.html.erb
<div class="dashboard-page">

  <div class="dashboard-content">
    <div class="dashboard-header my-5">
      <div class="dashboard-heading">
        <h2>Your Dashboard, <%= current_user.first_name %></h2>
      </div>

    <% unless current_user.recommendations.empty? %>
      <div class="dashboard-header-button">
        <div class="button-pri button-pri-dashboard">
          <%= link_to "Retake the quiz", assessment_path %>
        </div>
       </div>
    <% end %>

      </div>

    <div class="tabs-content">
      <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
          <button class="nav-link <%= "active" if params[:tab].nil? %>" id="nav-overview-tab" data-bs-toggle="tab" data-bs-target="#nav-overview" type="button" role="tab" aria-controls="nav-overview" aria-selected="true">Overview</button>
          <button class="nav-link <%= "active" if params[:tab] == 'Skills' %>" id="nav-skills-tab" data-bs-toggle="tab" data-bs-target="#nav-skills" type="button" role="tab" aria-controls="nav-skills" aria-selected="false">Skills</button>
          <button class="nav-link <%= "active" if params[:tab] == 'Values' %>" id="nav-values-tab" data-bs-toggle="tab" data-bs-target="#nav-values" type="button" role="tab" aria-controls="nav-values" aria-selected="false">Values</button>
        </div>
      </nav>

      <div class="tab-content" id="nav-tabContent">

        <div class="tab-pane fade  <%= "show active" if params[:tab].nil? %>" id="nav-overview" role="tabpanel" aria-labelledby="nav-overview-tab">
          <%= render "dashboards/overviewtab" %>
        </div>

        <div class="tab-pane fade <%= "show active" if params[:tab] == 'Skills' %>" id="nav-skills" role="tabpanel" aria-labelledby="nav-skills-tab">
          <%= render "dashboards/skillstab" %>
        </div>

        <div class="tab-pane fade <%= "show active" if params[:tab] == 'Values' %>" id="nav-values" role="tabpanel" aria-labelledby="nav-values-tab">
          <%= render "dashboards/valuestab" %>
        </div>

      </div>
    </div>
  </div>
</div>